name: Deploy docs

on:
    workflow_run:
        workflows: ["release"] # Must match the exact `name:` inside release.yml
        types:
            - completed

permissions:
    contents: read
    pages: write
    id-token: write
    actions: read

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build-and-deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Install Rust toolchain
              uses: dtolnay/rust-toolchain@stable

            - name: Setup Rust cache
              uses: Swatinem/rust-cache@v2
              with:
                  cache-all-crates: true

            - name: Cache Bun dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Generate rustdocs
              run: cargo doc-all

            - name: Copy Rustdoc to Rspress public directory
              run: |
                  mkdir -p docs/public/rustdoc
                  cp -r target/doc/* docs/public/rustdoc/

            - name: Install frontend dependencies
              working-directory: docs
              run: bun install

            - name: Build docs
              working-directory: docs
              run: bun run build

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "docs/doc_build"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
