name: Deploy docs

on:
    workflow_run:
        workflows: ["release"] # Must match the exact `name:` inside release.yml
        types:
            - completed

permissions:
    contents: read
    pages: write
    id-token: write
    actions: read

concurrency:
    group: "pages"
    cancel-in-progress: true

jobs:
    build-and-deploy:
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        runs-on: ubuntu-latest
        steps:
            - name: Cache Bun dependencies
              uses: actions/cache@v4
              with:
                  path: ~/.bun/install/cache
                  key: ${{ runner.os }}-bun-${{ hashFiles('**/bun.lockb') }}
                  restore-keys: |
                      ${{ runner.os }}-bun-

            - name: Setup Bun
              uses: oven-sh/setup-bun@v2
              with:
                  bun-version: latest

            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install frontend dependencies
              run: bun install

            - name: Fetch Release Tag Name
              id: release_info
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  HEAD_BRANCH="${{ github.event.workflow_run.head_branch }}"
                  echo "tag=$HEAD_BRANCH" >> $GITHUB_OUTPUT

            - name: Download rustdocs archive from release
              env:
                  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  mkdir -p tmp_download
                  gh release download "${{ steps.release_info.outputs.tag }}" \
                  --dir tmp_download \
                  --pattern "*extra-artifact*" || \
                  gh release download "${{ steps.release_info.outputs.tag }}" \
                  --dir tmp_download \
                  --pattern "*.tar.gz"

            - name: Extract archive
              run: |
                  mkdir -p public/rustdoc
                  ARCHIVE=$(find tmp_download -type f \( -name "*.tar.gz" -o -name "*.tar.xz" -o -name "*.zip" \) | head -n 1)

                  if [[ "$ARCHIVE" == *.zip ]]; then
                  unzip "$ARCHIVE" -d public/rustdoc
                  else
                  tar -xf "$ARCHIVE" -C public/rustdoc --strip-components=1
                  fi

            - name: Build docs
              run: bun run build

            - name: Upload Pages artifact
              uses: actions/upload-pages-artifact@v3
              with:
                  path: "./doc_build"

            - name: Deploy to GitHub Pages
              id: deployment
              uses: actions/deploy-pages@v4
